POST https://borneofood.app/api/register HTTP/1.1
Content-Type: application/json

{
    "name": "Ibrahim",
    "email": "ibrahim@mail.com",
    "password": "password",
    "password_confirmation": "password"
}

###
POST https://borneofood.app/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "ibrahim@mail.com",
    "password": "password"
}

###
GET https://borneofood.app/api/user HTTP/1.1
Authorization: Beaerer 1|cro3NUbdNjrLykyz7U8LgZgKlfxNu9pLQyMan1pr
