POST http://borneofood.test/api/register HTTP/1.1
Content-Type: application/json

{
    "name": "Ibrahim",
    "email": "ibrahim@mail.com",
    "password": "password",
    "password_confirmation": "password"
}

###
POST http://borneofood.test/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "ibrahim@mail.com",
    "password": "password"
}

###
GET http://borneofood.test/api/user HTTP/1.1
Authorization: Bearer 2|BwxALqdt38i7Y3dU59fhp3RWdRTZSzfGuzDv6pWj

###

POST http://borneofood.test/api/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer 2|BwxALqdt38i7Y3dU59fhp3RWdRTZSzfGuzDv6pWj

{
    "name": "Olahan"
}

###
GET http://borneofood.test/api/categories HTTP/1.1
Authorization: Bearer 2|BwxALqdt38i7Y3dU59fhp3RWdRTZSzfGuzDv6pWj
###
POST http://borneofood.test/api/foods HTTP/1.1
Content-Type: application/json
Authorization: Bearer 2|BwxALqdt38i7Y3dU59fhp3RWdRTZSzfGuzDv6pWj

{
    "name" : "Daging",
    "price": 10000,
    "stock": 10,
    "category_id": 1
}

###
GET http://borneofood.test/api/foods HTTP/1.1
Authorization: Bearer 2|BwxALqdt38i7Y3dU59fhp3RWdRTZSzfGuzDv6pWj
